"""initial

Revision ID: eb6280c6b232
Revises: 
Create Date: 2026-10-03 09:24:00.298512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6280c6b232'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('experience_level', sa.String(), nullable=False),
    sa.Column('bodyweight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=True),
    sa.Column('methodology', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('program_data', sa.JSON(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('exercise', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adaptation_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('previous_weight_kg', sa.Float(), nullable=False),
    sa.Column('recommended_weight_kg', sa.Float(), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=False),
    sa.Column('predicted_rpe', sa.Float(), nullable=False),
    sa.Column('expected_rpe', sa.Float(), nullable=False),
    sa.Column('rpe_delta', sa.Float(), nullable=False),
    sa.Column('adjustment_percent', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=False),
    sa.Column('planned_weight_kg', sa.Float(), nullable=False),
    sa.Column('planned_reps', sa.Integer(), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('athlete_rpe', sa.Float(), nullable=True),
    sa.Column('video_ref', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('set_id', sa.String(), nullable=True),
    sa.Column('predicted_rpe', sa.Float(), nullable=False),
    sa.Column('technique_score', sa.Float(), nullable=False),
    sa.Column('rom_score', sa.Float(), nullable=False),
    sa.Column('tempo_score', sa.Float(), nullable=False),
    sa.Column('bar_path_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analysis_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['workout_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('workout_sets')
    op.drop_table('adaptation_decisions')
    op.drop_table('workout_sessions')
    op.drop_table('programs')
    op.drop_table('athletes')
    # ### end Alembic commands ###
